# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'S9LedMapping.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(703, 535)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.watch_table_view = QtWidgets.QTableView(self.centralwidget)
        self.watch_table_view.setAutoScroll(True)
        self.watch_table_view.setObjectName("watch_table_view")
        self.watch_table_view.horizontalHeader().setVisible(False)
        self.watch_table_view.horizontalHeader().setCascadingSectionResizes(False)
        self.watch_table_view.horizontalHeader().setDefaultSectionSize(15)
        self.watch_table_view.horizontalHeader().setMinimumSectionSize(15)
        self.watch_table_view.horizontalHeader().setStretchLastSection(True)
        self.watch_table_view.verticalHeader().setVisible(False)
        self.watch_table_view.verticalHeader().setCascadingSectionResizes(False)
        self.watch_table_view.verticalHeader().setDefaultSectionSize(15)
        self.watch_table_view.verticalHeader().setMinimumSectionSize(15)
        self.watch_table_view.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.watch_table_view)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.plainTextEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_powon = QtWidgets.QPushButton(self.centralwidget)
        self.btn_powon.setObjectName("btn_powon")
        self.horizontalLayout.addWidget(self.btn_powon)
        self.btn_wifi = QtWidgets.QPushButton(self.centralwidget)
        self.btn_wifi.setObjectName("btn_wifi")
        self.horizontalLayout.addWidget(self.btn_wifi)
        self.btn_ble = QtWidgets.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btn_ble.setPalette(palette)
        self.btn_ble.setObjectName("btn_ble")
        self.horizontalLayout.addWidget(self.btn_ble)
        self.btn_kg = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kg.setObjectName("btn_kg")
        self.horizontalLayout.addWidget(self.btn_kg)
        self.btn_lb = QtWidgets.QPushButton(self.centralwidget)
        self.btn_lb.setObjectName("btn_lb")
        self.horizontalLayout.addWidget(self.btn_lb)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_2.addWidget(self.btn_reset)
        self.comboBox_ser = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ser.setObjectName("comboBox_ser")
        self.horizontalLayout_2.addWidget(self.comboBox_ser)
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_2.addWidget(self.btn_send)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "S9_LedMapping"))
        self.btn_powon.setText(_translate("MainWindow", "充电"))
        self.btn_wifi.setText(_translate("MainWindow", "WIFI"))
        self.btn_ble.setText(_translate("MainWindow", "BLE"))
        self.btn_kg.setText(_translate("MainWindow", "KG"))
        self.btn_lb.setText(_translate("MainWindow", "LB"))
        self.btn_reset.setText(_translate("MainWindow", "恢复默认"))
        self.comboBox_ser.setToolTip(_translate("MainWindow", "选择要使用的端口号"))
        self.btn_send.setToolTip(_translate("MainWindow", "更新数据, 请先选择端口号。"))
        self.btn_send.setText(_translate("MainWindow", "发送数据"))

